### ISSUE TITLE
Migrate to null safety 

### ISSUE THREAD

**Issue by kw2019ltd** [fluttercommunity/flutter_after_layout#15]
Description

All dependencies are migrated to null safety. So we should migrate this package to null safety.
Resources

https://www.youtube.com/watch?v=eBr5tlumwlg&feature=youtu.be
https://medium.com/dartlang/announcing-dart-null-safety-beta-87610fee6730

**Comment by nipunasudha** [comment]
This package is last updated in 2019, I don't think there will be an immediate update. There are only 15 lines of code in here. I'm just gonna create a new mixin with that code, for now at least!

![image](https://user-images.githubusercontent.com/17500323/110388879-c2159000-8089-11eb-983a-c9921e056618.png)

**Comment by nico85** [comment]
> This package is last updated in 2019, I don't think there will be an immediate update. There are only 15 lines of code in here. I'm just gonna create a new mixin with that code, for now at least!
> 
> ![image](https://user-images.githubusercontent.com/17500323/110388879-c2159000-8089-11eb-983a-c9921e056618.png)


If you would kindly tell me how to do that? or if you made a fork would you pass me the git? i'm new to flutter and i use this mixin, thanks!

**Comment by nipunasudha** [comment]
> > This package is last updated in 2019, I don't think there will be an immediate update. There are only 15 lines of code in here. I'm just gonna create a new mixin with that code, for now at least!
> > ![image](https://user-images.githubusercontent.com/17500323/110388879-c2159000-8089-11eb-983a-c9921e056618.png)
> 
> If you would kindly tell me how to do that? or if you made a fork would you pass me the git? i'm new to flutter and i use this mixin, thanks!

Since this is a very simple single file package, I created a new file called 'after_layout_mixin.dart' in my project, and copy pasted the code from here -> https://github.com/fluttercommunity/flutter_after_layout/blob/53abdd3205ad8c9d275a38b02914041bc8c340d6/lib/after_layout.dart

Remove this package from pubspec & import your own mixin instead. When migrating to null safety using the migrate tool, Flutter will automatically add nullsafety to your new mixin. 

Note: this is not a good thing to do if the package is a big & complex one, but since this package is only 15 lines, you can do that without consequences.

**Comment by slightfoot** [comment]
Published new null-safe version v1.1.0.
